// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptu.proto

#include "ptu.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ptu {
PROTOBUF_CONSTEXPR PTUStatus::PTUStatus(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pan_units_)*/0
  , /*decltype(_impl_.tilt_units_)*/0
  , /*decltype(_impl_.pan_degrees_per_unit_)*/0
  , /*decltype(_impl_.tilt_degrees_per_unit_)*/0
  , /*decltype(_impl_.pan_heading_)*/0
  , /*decltype(_impl_.tilt_heading_)*/0
  , /*decltype(_impl_.port_)*/0
  , /*decltype(_impl_.pan_min_deg_)*/0
  , /*decltype(_impl_.pan_max_deg_)*/0
  , /*decltype(_impl_.tilt_min_deg_)*/0
  , /*decltype(_impl_.tilt_max_deg_)*/0
  , /*decltype(_impl_.pan_speed_)*/0
  , /*decltype(_impl_.tilt_speed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PTUStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PTUStatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PTUStatusDefaultTypeInternal() {}
  union {
    PTUStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PTUStatusDefaultTypeInternal _PTUStatus_default_instance_;
PROTOBUF_CONSTEXPR PTUCommand::PTUCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_)*/0
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PTUCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PTUCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PTUCommandDefaultTypeInternal() {}
  union {
    PTUCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PTUCommandDefaultTypeInternal _PTUCommand_default_instance_;
}  // namespace ptu
static ::_pb::Metadata file_level_metadata_ptu_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ptu_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ptu_2eproto = nullptr;

const uint32_t TableStruct_ptu_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _split_
  ~0u,  // no sizeof(Split)
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_units_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_units_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_degrees_per_unit_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_degrees_per_unit_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_heading_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_heading_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_min_deg_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_max_deg_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_min_deg_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_max_deg_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.pan_speed_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUStatus, _impl_.tilt_speed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ptu::PTUCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _split_
  ~0u,  // no sizeof(Split)
  PROTOBUF_FIELD_OFFSET(::ptu::PTUCommand, _impl_.command_),
  PROTOBUF_FIELD_OFFSET(::ptu::PTUCommand, _impl_.value_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ptu::PTUStatus)},
  { 21, -1, -1, sizeof(::ptu::PTUCommand)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ptu::_PTUStatus_default_instance_._instance,
  &::ptu::_PTUCommand_default_instance_._instance,
};

const char descriptor_table_protodef_ptu_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tptu.proto\022\003ptu\"\245\002\n\tPTUStatus\022\021\n\tpan_un"
  "its\030\001 \001(\005\022\022\n\ntilt_units\030\002 \001(\005\022\034\n\024pan_deg"
  "rees_per_unit\030\003 \001(\001\022\035\n\025tilt_degrees_per_"
  "unit\030\004 \001(\001\022\023\n\013pan_heading\030\005 \001(\005\022\024\n\014tilt_"
  "heading\030\006 \001(\005\022\014\n\004port\030\007 \001(\005\022\023\n\013pan_min_d"
  "eg\030\010 \001(\005\022\023\n\013pan_max_deg\030\t \001(\005\022\024\n\014tilt_mi"
  "n_deg\030\n \001(\005\022\024\n\014tilt_max_deg\030\013 \001(\005\022\021\n\tpan"
  "_speed\030\014 \001(\005\022\022\n\ntilt_speed\030\r \001(\005\":\n\nPTUC"
  "ommand\022\035\n\007command\030\001 \001(\0162\014.ptu.PTUType\022\r\n"
  "\005value\030\002 \001(\005*p\n\007PTUType\022\013\n\007UNKNOWN\020\000\022\010\n\004"
  "HOME\020\001\022\010\n\004STOP\020\002\022\013\n\007SET_PAN\020\003\022\014\n\010SET_TIL"
  "T\020\004\022\023\n\017SET_PAN_HEADING\020\005\022\024\n\020SET_TILT_HEA"
  "DING\020\006b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ptu_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ptu_2eproto = {
    false, false, 494, descriptor_table_protodef_ptu_2eproto,
    "ptu.proto",
    &descriptor_table_ptu_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_ptu_2eproto::offsets,
    file_level_metadata_ptu_2eproto, file_level_enum_descriptors_ptu_2eproto,
    file_level_service_descriptors_ptu_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ptu_2eproto_getter() {
  return &descriptor_table_ptu_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ptu_2eproto(&descriptor_table_ptu_2eproto);
namespace ptu {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PTUType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ptu_2eproto);
  return file_level_enum_descriptors_ptu_2eproto[0];
}
bool PTUType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class PTUStatus::_Internal {
 public:
};

PTUStatus::PTUStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ptu.PTUStatus)
}
PTUStatus::PTUStatus(const PTUStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PTUStatus* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pan_units_){}
    , decltype(_impl_.tilt_units_){}
    , decltype(_impl_.pan_degrees_per_unit_){}
    , decltype(_impl_.tilt_degrees_per_unit_){}
    , decltype(_impl_.pan_heading_){}
    , decltype(_impl_.tilt_heading_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.pan_min_deg_){}
    , decltype(_impl_.pan_max_deg_){}
    , decltype(_impl_.tilt_min_deg_){}
    , decltype(_impl_.tilt_max_deg_){}
    , decltype(_impl_.pan_speed_){}
    , decltype(_impl_.tilt_speed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.pan_units_, &from._impl_.pan_units_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.tilt_speed_) -
    reinterpret_cast<char*>(&_impl_.pan_units_)) + sizeof(_impl_.tilt_speed_));
  // @@protoc_insertion_point(copy_constructor:ptu.PTUStatus)
}

inline void PTUStatus::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pan_units_){0}
    , decltype(_impl_.tilt_units_){0}
    , decltype(_impl_.pan_degrees_per_unit_){0}
    , decltype(_impl_.tilt_degrees_per_unit_){0}
    , decltype(_impl_.pan_heading_){0}
    , decltype(_impl_.tilt_heading_){0}
    , decltype(_impl_.port_){0}
    , decltype(_impl_.pan_min_deg_){0}
    , decltype(_impl_.pan_max_deg_){0}
    , decltype(_impl_.tilt_min_deg_){0}
    , decltype(_impl_.tilt_max_deg_){0}
    , decltype(_impl_.pan_speed_){0}
    , decltype(_impl_.tilt_speed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PTUStatus::~PTUStatus() {
  // @@protoc_insertion_point(destructor:ptu.PTUStatus)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PTUStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PTUStatus::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PTUStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:ptu.PTUStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.pan_units_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.tilt_speed_) -
      reinterpret_cast<char*>(&_impl_.pan_units_)) + sizeof(_impl_.tilt_speed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PTUStatus::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 pan_units = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.pan_units_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tilt_units = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tilt_units_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double pan_degrees_per_unit = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.pan_degrees_per_unit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double tilt_degrees_per_unit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.tilt_degrees_per_unit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 pan_heading = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.pan_heading_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tilt_heading = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.tilt_heading_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 port = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pan_min_deg = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.pan_min_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pan_max_deg = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.pan_max_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tilt_min_deg = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.tilt_min_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tilt_max_deg = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.tilt_max_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pan_speed = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.pan_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tilt_speed = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _impl_.tilt_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PTUStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ptu.PTUStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 pan_units = 1;
  if (this->_internal_pan_units() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_pan_units(), target);
  }

  // int32 tilt_units = 2;
  if (this->_internal_tilt_units() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_tilt_units(), target);
  }

  // double pan_degrees_per_unit = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pan_degrees_per_unit = this->_internal_pan_degrees_per_unit();
  uint64_t raw_pan_degrees_per_unit;
  memcpy(&raw_pan_degrees_per_unit, &tmp_pan_degrees_per_unit, sizeof(tmp_pan_degrees_per_unit));
  if (raw_pan_degrees_per_unit != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_pan_degrees_per_unit(), target);
  }

  // double tilt_degrees_per_unit = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tilt_degrees_per_unit = this->_internal_tilt_degrees_per_unit();
  uint64_t raw_tilt_degrees_per_unit;
  memcpy(&raw_tilt_degrees_per_unit, &tmp_tilt_degrees_per_unit, sizeof(tmp_tilt_degrees_per_unit));
  if (raw_tilt_degrees_per_unit != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_tilt_degrees_per_unit(), target);
  }

  // int32 pan_heading = 5;
  if (this->_internal_pan_heading() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_pan_heading(), target);
  }

  // int32 tilt_heading = 6;
  if (this->_internal_tilt_heading() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_tilt_heading(), target);
  }

  // int32 port = 7;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_port(), target);
  }

  // int32 pan_min_deg = 8;
  if (this->_internal_pan_min_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_pan_min_deg(), target);
  }

  // int32 pan_max_deg = 9;
  if (this->_internal_pan_max_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_pan_max_deg(), target);
  }

  // int32 tilt_min_deg = 10;
  if (this->_internal_tilt_min_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_tilt_min_deg(), target);
  }

  // int32 tilt_max_deg = 11;
  if (this->_internal_tilt_max_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(11, this->_internal_tilt_max_deg(), target);
  }

  // int32 pan_speed = 12;
  if (this->_internal_pan_speed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(12, this->_internal_pan_speed(), target);
  }

  // int32 tilt_speed = 13;
  if (this->_internal_tilt_speed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(13, this->_internal_tilt_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ptu.PTUStatus)
  return target;
}

size_t PTUStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ptu.PTUStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 pan_units = 1;
  if (this->_internal_pan_units() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pan_units());
  }

  // int32 tilt_units = 2;
  if (this->_internal_tilt_units() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tilt_units());
  }

  // double pan_degrees_per_unit = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pan_degrees_per_unit = this->_internal_pan_degrees_per_unit();
  uint64_t raw_pan_degrees_per_unit;
  memcpy(&raw_pan_degrees_per_unit, &tmp_pan_degrees_per_unit, sizeof(tmp_pan_degrees_per_unit));
  if (raw_pan_degrees_per_unit != 0) {
    total_size += 1 + 8;
  }

  // double tilt_degrees_per_unit = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tilt_degrees_per_unit = this->_internal_tilt_degrees_per_unit();
  uint64_t raw_tilt_degrees_per_unit;
  memcpy(&raw_tilt_degrees_per_unit, &tmp_tilt_degrees_per_unit, sizeof(tmp_tilt_degrees_per_unit));
  if (raw_tilt_degrees_per_unit != 0) {
    total_size += 1 + 8;
  }

  // int32 pan_heading = 5;
  if (this->_internal_pan_heading() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pan_heading());
  }

  // int32 tilt_heading = 6;
  if (this->_internal_tilt_heading() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tilt_heading());
  }

  // int32 port = 7;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_port());
  }

  // int32 pan_min_deg = 8;
  if (this->_internal_pan_min_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pan_min_deg());
  }

  // int32 pan_max_deg = 9;
  if (this->_internal_pan_max_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pan_max_deg());
  }

  // int32 tilt_min_deg = 10;
  if (this->_internal_tilt_min_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tilt_min_deg());
  }

  // int32 tilt_max_deg = 11;
  if (this->_internal_tilt_max_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tilt_max_deg());
  }

  // int32 pan_speed = 12;
  if (this->_internal_pan_speed() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pan_speed());
  }

  // int32 tilt_speed = 13;
  if (this->_internal_tilt_speed() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tilt_speed());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PTUStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PTUStatus::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PTUStatus::GetClassData() const { return &_class_data_; }


void PTUStatus::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PTUStatus*>(&to_msg);
  auto& from = static_cast<const PTUStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ptu.PTUStatus)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_pan_units() != 0) {
    _this->_internal_set_pan_units(from._internal_pan_units());
  }
  if (from._internal_tilt_units() != 0) {
    _this->_internal_set_tilt_units(from._internal_tilt_units());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_pan_degrees_per_unit = from._internal_pan_degrees_per_unit();
  uint64_t raw_pan_degrees_per_unit;
  memcpy(&raw_pan_degrees_per_unit, &tmp_pan_degrees_per_unit, sizeof(tmp_pan_degrees_per_unit));
  if (raw_pan_degrees_per_unit != 0) {
    _this->_internal_set_pan_degrees_per_unit(from._internal_pan_degrees_per_unit());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tilt_degrees_per_unit = from._internal_tilt_degrees_per_unit();
  uint64_t raw_tilt_degrees_per_unit;
  memcpy(&raw_tilt_degrees_per_unit, &tmp_tilt_degrees_per_unit, sizeof(tmp_tilt_degrees_per_unit));
  if (raw_tilt_degrees_per_unit != 0) {
    _this->_internal_set_tilt_degrees_per_unit(from._internal_tilt_degrees_per_unit());
  }
  if (from._internal_pan_heading() != 0) {
    _this->_internal_set_pan_heading(from._internal_pan_heading());
  }
  if (from._internal_tilt_heading() != 0) {
    _this->_internal_set_tilt_heading(from._internal_tilt_heading());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_pan_min_deg() != 0) {
    _this->_internal_set_pan_min_deg(from._internal_pan_min_deg());
  }
  if (from._internal_pan_max_deg() != 0) {
    _this->_internal_set_pan_max_deg(from._internal_pan_max_deg());
  }
  if (from._internal_tilt_min_deg() != 0) {
    _this->_internal_set_tilt_min_deg(from._internal_tilt_min_deg());
  }
  if (from._internal_tilt_max_deg() != 0) {
    _this->_internal_set_tilt_max_deg(from._internal_tilt_max_deg());
  }
  if (from._internal_pan_speed() != 0) {
    _this->_internal_set_pan_speed(from._internal_pan_speed());
  }
  if (from._internal_tilt_speed() != 0) {
    _this->_internal_set_tilt_speed(from._internal_tilt_speed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PTUStatus::CopyFrom(const PTUStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ptu.PTUStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PTUStatus::IsInitialized() const {
  return true;
}

void PTUStatus::InternalSwap(PTUStatus* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PTUStatus, _impl_.tilt_speed_)
      + sizeof(PTUStatus::_impl_.tilt_speed_)
      - PROTOBUF_FIELD_OFFSET(PTUStatus, _impl_.pan_units_)>(
          reinterpret_cast<char*>(&_impl_.pan_units_),
          reinterpret_cast<char*>(&other->_impl_.pan_units_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PTUStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptu_2eproto_getter, &descriptor_table_ptu_2eproto_once,
      file_level_metadata_ptu_2eproto[0]);
}

// ===================================================================

class PTUCommand::_Internal {
 public:
};

PTUCommand::PTUCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ptu.PTUCommand)
}
PTUCommand::PTUCommand(const PTUCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PTUCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.command_, &from._impl_.command_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.value_) -
    reinterpret_cast<char*>(&_impl_.command_)) + sizeof(_impl_.value_));
  // @@protoc_insertion_point(copy_constructor:ptu.PTUCommand)
}

inline void PTUCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){0}
    , decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PTUCommand::~PTUCommand() {
  // @@protoc_insertion_point(destructor:ptu.PTUCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PTUCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PTUCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PTUCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:ptu.PTUCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.command_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.value_) -
      reinterpret_cast<char*>(&_impl_.command_)) + sizeof(_impl_.value_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PTUCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ptu.PTUType command = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_command(static_cast<::ptu::PTUType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PTUCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ptu.PTUCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ptu.PTUType command = 1;
  if (this->_internal_command() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_command(), target);
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ptu.PTUCommand)
  return target;
}

size_t PTUCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ptu.PTUCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .ptu.PTUType command = 1;
  if (this->_internal_command() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_command());
  }

  // int32 value = 2;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PTUCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PTUCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PTUCommand::GetClassData() const { return &_class_data_; }


void PTUCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PTUCommand*>(&to_msg);
  auto& from = static_cast<const PTUCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ptu.PTUCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_command() != 0) {
    _this->_internal_set_command(from._internal_command());
  }
  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PTUCommand::CopyFrom(const PTUCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ptu.PTUCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PTUCommand::IsInitialized() const {
  return true;
}

void PTUCommand::InternalSwap(PTUCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PTUCommand, _impl_.value_)
      + sizeof(PTUCommand::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(PTUCommand, _impl_.command_)>(
          reinterpret_cast<char*>(&_impl_.command_),
          reinterpret_cast<char*>(&other->_impl_.command_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PTUCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptu_2eproto_getter, &descriptor_table_ptu_2eproto_once,
      file_level_metadata_ptu_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ptu
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ptu::PTUStatus*
Arena::CreateMaybeMessage< ::ptu::PTUStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ptu::PTUStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::ptu::PTUCommand*
Arena::CreateMaybeMessage< ::ptu::PTUCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ptu::PTUCommand >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
