// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ptu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ptu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ptu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ptu_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ptu_2eproto;
namespace ptu {
class PTUCommand;
struct PTUCommandDefaultTypeInternal;
extern PTUCommandDefaultTypeInternal _PTUCommand_default_instance_;
class PTUStatus;
struct PTUStatusDefaultTypeInternal;
extern PTUStatusDefaultTypeInternal _PTUStatus_default_instance_;
}  // namespace ptu
PROTOBUF_NAMESPACE_OPEN
template<> ::ptu::PTUCommand* Arena::CreateMaybeMessage<::ptu::PTUCommand>(Arena*);
template<> ::ptu::PTUStatus* Arena::CreateMaybeMessage<::ptu::PTUStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ptu {

enum PTUType : int {
  UNKNOWN = 0,
  HOME = 1,
  STOP = 2,
  SET_PAN = 3,
  SET_TILT = 4,
  SET_PAN_HEADING = 5,
  SET_TILT_HEADING = 6,
  PTUType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PTUType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PTUType_IsValid(int value);
constexpr PTUType PTUType_MIN = UNKNOWN;
constexpr PTUType PTUType_MAX = SET_TILT_HEADING;
constexpr int PTUType_ARRAYSIZE = PTUType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PTUType_descriptor();
template<typename T>
inline const std::string& PTUType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PTUType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PTUType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PTUType_descriptor(), enum_t_value);
}
inline bool PTUType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PTUType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PTUType>(
    PTUType_descriptor(), name, value);
}
// ===================================================================

class PTUStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ptu.PTUStatus) */ {
 public:
  inline PTUStatus() : PTUStatus(nullptr) {}
  ~PTUStatus() override;
  explicit PROTOBUF_CONSTEXPR PTUStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PTUStatus(const PTUStatus& from);
  PTUStatus(PTUStatus&& from) noexcept
    : PTUStatus() {
    *this = ::std::move(from);
  }

  inline PTUStatus& operator=(const PTUStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTUStatus& operator=(PTUStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PTUStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const PTUStatus* internal_default_instance() {
    return reinterpret_cast<const PTUStatus*>(
               &_PTUStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PTUStatus& a, PTUStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(PTUStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTUStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PTUStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PTUStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PTUStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PTUStatus& from) {
    PTUStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PTUStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ptu.PTUStatus";
  }
  protected:
  explicit PTUStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPanUnitsFieldNumber = 1,
    kTiltUnitsFieldNumber = 2,
    kPanDegreesPerUnitFieldNumber = 3,
    kTiltDegreesPerUnitFieldNumber = 4,
    kPanHeadingFieldNumber = 5,
    kTiltHeadingFieldNumber = 6,
    kPortFieldNumber = 7,
    kPanMinDegFieldNumber = 8,
    kPanMaxDegFieldNumber = 9,
    kTiltMinDegFieldNumber = 10,
    kTiltMaxDegFieldNumber = 11,
    kPanSpeedFieldNumber = 12,
    kTiltSpeedFieldNumber = 13,
  };
  // int32 pan_units = 1;
  void clear_pan_units();
  int32_t pan_units() const;
  void set_pan_units(int32_t value);
  private:
  int32_t _internal_pan_units() const;
  void _internal_set_pan_units(int32_t value);
  public:

  // int32 tilt_units = 2;
  void clear_tilt_units();
  int32_t tilt_units() const;
  void set_tilt_units(int32_t value);
  private:
  int32_t _internal_tilt_units() const;
  void _internal_set_tilt_units(int32_t value);
  public:

  // double pan_degrees_per_unit = 3;
  void clear_pan_degrees_per_unit();
  double pan_degrees_per_unit() const;
  void set_pan_degrees_per_unit(double value);
  private:
  double _internal_pan_degrees_per_unit() const;
  void _internal_set_pan_degrees_per_unit(double value);
  public:

  // double tilt_degrees_per_unit = 4;
  void clear_tilt_degrees_per_unit();
  double tilt_degrees_per_unit() const;
  void set_tilt_degrees_per_unit(double value);
  private:
  double _internal_tilt_degrees_per_unit() const;
  void _internal_set_tilt_degrees_per_unit(double value);
  public:

  // int32 pan_heading = 5;
  void clear_pan_heading();
  int32_t pan_heading() const;
  void set_pan_heading(int32_t value);
  private:
  int32_t _internal_pan_heading() const;
  void _internal_set_pan_heading(int32_t value);
  public:

  // int32 tilt_heading = 6;
  void clear_tilt_heading();
  int32_t tilt_heading() const;
  void set_tilt_heading(int32_t value);
  private:
  int32_t _internal_tilt_heading() const;
  void _internal_set_tilt_heading(int32_t value);
  public:

  // int32 port = 7;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // int32 pan_min_deg = 8;
  void clear_pan_min_deg();
  int32_t pan_min_deg() const;
  void set_pan_min_deg(int32_t value);
  private:
  int32_t _internal_pan_min_deg() const;
  void _internal_set_pan_min_deg(int32_t value);
  public:

  // int32 pan_max_deg = 9;
  void clear_pan_max_deg();
  int32_t pan_max_deg() const;
  void set_pan_max_deg(int32_t value);
  private:
  int32_t _internal_pan_max_deg() const;
  void _internal_set_pan_max_deg(int32_t value);
  public:

  // int32 tilt_min_deg = 10;
  void clear_tilt_min_deg();
  int32_t tilt_min_deg() const;
  void set_tilt_min_deg(int32_t value);
  private:
  int32_t _internal_tilt_min_deg() const;
  void _internal_set_tilt_min_deg(int32_t value);
  public:

  // int32 tilt_max_deg = 11;
  void clear_tilt_max_deg();
  int32_t tilt_max_deg() const;
  void set_tilt_max_deg(int32_t value);
  private:
  int32_t _internal_tilt_max_deg() const;
  void _internal_set_tilt_max_deg(int32_t value);
  public:

  // int32 pan_speed = 12;
  void clear_pan_speed();
  int32_t pan_speed() const;
  void set_pan_speed(int32_t value);
  private:
  int32_t _internal_pan_speed() const;
  void _internal_set_pan_speed(int32_t value);
  public:

  // int32 tilt_speed = 13;
  void clear_tilt_speed();
  int32_t tilt_speed() const;
  void set_tilt_speed(int32_t value);
  private:
  int32_t _internal_tilt_speed() const;
  void _internal_set_tilt_speed(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ptu.PTUStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t pan_units_;
    int32_t tilt_units_;
    double pan_degrees_per_unit_;
    double tilt_degrees_per_unit_;
    int32_t pan_heading_;
    int32_t tilt_heading_;
    int32_t port_;
    int32_t pan_min_deg_;
    int32_t pan_max_deg_;
    int32_t tilt_min_deg_;
    int32_t tilt_max_deg_;
    int32_t pan_speed_;
    int32_t tilt_speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ptu_2eproto;
};
// -------------------------------------------------------------------

class PTUCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ptu.PTUCommand) */ {
 public:
  inline PTUCommand() : PTUCommand(nullptr) {}
  ~PTUCommand() override;
  explicit PROTOBUF_CONSTEXPR PTUCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PTUCommand(const PTUCommand& from);
  PTUCommand(PTUCommand&& from) noexcept
    : PTUCommand() {
    *this = ::std::move(from);
  }

  inline PTUCommand& operator=(const PTUCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTUCommand& operator=(PTUCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PTUCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const PTUCommand* internal_default_instance() {
    return reinterpret_cast<const PTUCommand*>(
               &_PTUCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PTUCommand& a, PTUCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(PTUCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTUCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PTUCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PTUCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PTUCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PTUCommand& from) {
    PTUCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PTUCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ptu.PTUCommand";
  }
  protected:
  explicit PTUCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // .ptu.PTUType command = 1;
  void clear_command();
  ::ptu::PTUType command() const;
  void set_command(::ptu::PTUType value);
  private:
  ::ptu::PTUType _internal_command() const;
  void _internal_set_command(::ptu::PTUType value);
  public:

  // int32 value = 2;
  void clear_value();
  int32_t value() const;
  void set_value(int32_t value);
  private:
  int32_t _internal_value() const;
  void _internal_set_value(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ptu.PTUCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int command_;
    int32_t value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ptu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PTUStatus

// int32 pan_units = 1;
inline void PTUStatus::clear_pan_units() {
  _impl_.pan_units_ = 0;
}
inline int32_t PTUStatus::_internal_pan_units() const {
  return _impl_.pan_units_;
}
inline int32_t PTUStatus::pan_units() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_units)
  return _internal_pan_units();
}
inline void PTUStatus::_internal_set_pan_units(int32_t value) {
  
  _impl_.pan_units_ = value;
}
inline void PTUStatus::set_pan_units(int32_t value) {
  _internal_set_pan_units(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_units)
}

// int32 tilt_units = 2;
inline void PTUStatus::clear_tilt_units() {
  _impl_.tilt_units_ = 0;
}
inline int32_t PTUStatus::_internal_tilt_units() const {
  return _impl_.tilt_units_;
}
inline int32_t PTUStatus::tilt_units() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_units)
  return _internal_tilt_units();
}
inline void PTUStatus::_internal_set_tilt_units(int32_t value) {
  
  _impl_.tilt_units_ = value;
}
inline void PTUStatus::set_tilt_units(int32_t value) {
  _internal_set_tilt_units(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_units)
}

// double pan_degrees_per_unit = 3;
inline void PTUStatus::clear_pan_degrees_per_unit() {
  _impl_.pan_degrees_per_unit_ = 0;
}
inline double PTUStatus::_internal_pan_degrees_per_unit() const {
  return _impl_.pan_degrees_per_unit_;
}
inline double PTUStatus::pan_degrees_per_unit() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_degrees_per_unit)
  return _internal_pan_degrees_per_unit();
}
inline void PTUStatus::_internal_set_pan_degrees_per_unit(double value) {
  
  _impl_.pan_degrees_per_unit_ = value;
}
inline void PTUStatus::set_pan_degrees_per_unit(double value) {
  _internal_set_pan_degrees_per_unit(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_degrees_per_unit)
}

// double tilt_degrees_per_unit = 4;
inline void PTUStatus::clear_tilt_degrees_per_unit() {
  _impl_.tilt_degrees_per_unit_ = 0;
}
inline double PTUStatus::_internal_tilt_degrees_per_unit() const {
  return _impl_.tilt_degrees_per_unit_;
}
inline double PTUStatus::tilt_degrees_per_unit() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_degrees_per_unit)
  return _internal_tilt_degrees_per_unit();
}
inline void PTUStatus::_internal_set_tilt_degrees_per_unit(double value) {
  
  _impl_.tilt_degrees_per_unit_ = value;
}
inline void PTUStatus::set_tilt_degrees_per_unit(double value) {
  _internal_set_tilt_degrees_per_unit(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_degrees_per_unit)
}

// int32 pan_heading = 5;
inline void PTUStatus::clear_pan_heading() {
  _impl_.pan_heading_ = 0;
}
inline int32_t PTUStatus::_internal_pan_heading() const {
  return _impl_.pan_heading_;
}
inline int32_t PTUStatus::pan_heading() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_heading)
  return _internal_pan_heading();
}
inline void PTUStatus::_internal_set_pan_heading(int32_t value) {
  
  _impl_.pan_heading_ = value;
}
inline void PTUStatus::set_pan_heading(int32_t value) {
  _internal_set_pan_heading(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_heading)
}

// int32 tilt_heading = 6;
inline void PTUStatus::clear_tilt_heading() {
  _impl_.tilt_heading_ = 0;
}
inline int32_t PTUStatus::_internal_tilt_heading() const {
  return _impl_.tilt_heading_;
}
inline int32_t PTUStatus::tilt_heading() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_heading)
  return _internal_tilt_heading();
}
inline void PTUStatus::_internal_set_tilt_heading(int32_t value) {
  
  _impl_.tilt_heading_ = value;
}
inline void PTUStatus::set_tilt_heading(int32_t value) {
  _internal_set_tilt_heading(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_heading)
}

// int32 port = 7;
inline void PTUStatus::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t PTUStatus::_internal_port() const {
  return _impl_.port_;
}
inline int32_t PTUStatus::port() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.port)
  return _internal_port();
}
inline void PTUStatus::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void PTUStatus::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.port)
}

// int32 pan_min_deg = 8;
inline void PTUStatus::clear_pan_min_deg() {
  _impl_.pan_min_deg_ = 0;
}
inline int32_t PTUStatus::_internal_pan_min_deg() const {
  return _impl_.pan_min_deg_;
}
inline int32_t PTUStatus::pan_min_deg() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_min_deg)
  return _internal_pan_min_deg();
}
inline void PTUStatus::_internal_set_pan_min_deg(int32_t value) {
  
  _impl_.pan_min_deg_ = value;
}
inline void PTUStatus::set_pan_min_deg(int32_t value) {
  _internal_set_pan_min_deg(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_min_deg)
}

// int32 pan_max_deg = 9;
inline void PTUStatus::clear_pan_max_deg() {
  _impl_.pan_max_deg_ = 0;
}
inline int32_t PTUStatus::_internal_pan_max_deg() const {
  return _impl_.pan_max_deg_;
}
inline int32_t PTUStatus::pan_max_deg() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_max_deg)
  return _internal_pan_max_deg();
}
inline void PTUStatus::_internal_set_pan_max_deg(int32_t value) {
  
  _impl_.pan_max_deg_ = value;
}
inline void PTUStatus::set_pan_max_deg(int32_t value) {
  _internal_set_pan_max_deg(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_max_deg)
}

// int32 tilt_min_deg = 10;
inline void PTUStatus::clear_tilt_min_deg() {
  _impl_.tilt_min_deg_ = 0;
}
inline int32_t PTUStatus::_internal_tilt_min_deg() const {
  return _impl_.tilt_min_deg_;
}
inline int32_t PTUStatus::tilt_min_deg() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_min_deg)
  return _internal_tilt_min_deg();
}
inline void PTUStatus::_internal_set_tilt_min_deg(int32_t value) {
  
  _impl_.tilt_min_deg_ = value;
}
inline void PTUStatus::set_tilt_min_deg(int32_t value) {
  _internal_set_tilt_min_deg(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_min_deg)
}

// int32 tilt_max_deg = 11;
inline void PTUStatus::clear_tilt_max_deg() {
  _impl_.tilt_max_deg_ = 0;
}
inline int32_t PTUStatus::_internal_tilt_max_deg() const {
  return _impl_.tilt_max_deg_;
}
inline int32_t PTUStatus::tilt_max_deg() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_max_deg)
  return _internal_tilt_max_deg();
}
inline void PTUStatus::_internal_set_tilt_max_deg(int32_t value) {
  
  _impl_.tilt_max_deg_ = value;
}
inline void PTUStatus::set_tilt_max_deg(int32_t value) {
  _internal_set_tilt_max_deg(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_max_deg)
}

// int32 pan_speed = 12;
inline void PTUStatus::clear_pan_speed() {
  _impl_.pan_speed_ = 0;
}
inline int32_t PTUStatus::_internal_pan_speed() const {
  return _impl_.pan_speed_;
}
inline int32_t PTUStatus::pan_speed() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.pan_speed)
  return _internal_pan_speed();
}
inline void PTUStatus::_internal_set_pan_speed(int32_t value) {
  
  _impl_.pan_speed_ = value;
}
inline void PTUStatus::set_pan_speed(int32_t value) {
  _internal_set_pan_speed(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.pan_speed)
}

// int32 tilt_speed = 13;
inline void PTUStatus::clear_tilt_speed() {
  _impl_.tilt_speed_ = 0;
}
inline int32_t PTUStatus::_internal_tilt_speed() const {
  return _impl_.tilt_speed_;
}
inline int32_t PTUStatus::tilt_speed() const {
  // @@protoc_insertion_point(field_get:ptu.PTUStatus.tilt_speed)
  return _internal_tilt_speed();
}
inline void PTUStatus::_internal_set_tilt_speed(int32_t value) {
  
  _impl_.tilt_speed_ = value;
}
inline void PTUStatus::set_tilt_speed(int32_t value) {
  _internal_set_tilt_speed(value);
  // @@protoc_insertion_point(field_set:ptu.PTUStatus.tilt_speed)
}

// -------------------------------------------------------------------

// PTUCommand

// .ptu.PTUType command = 1;
inline void PTUCommand::clear_command() {
  _impl_.command_ = 0;
}
inline ::ptu::PTUType PTUCommand::_internal_command() const {
  return static_cast< ::ptu::PTUType >(_impl_.command_);
}
inline ::ptu::PTUType PTUCommand::command() const {
  // @@protoc_insertion_point(field_get:ptu.PTUCommand.command)
  return _internal_command();
}
inline void PTUCommand::_internal_set_command(::ptu::PTUType value) {
  
  _impl_.command_ = value;
}
inline void PTUCommand::set_command(::ptu::PTUType value) {
  _internal_set_command(value);
  // @@protoc_insertion_point(field_set:ptu.PTUCommand.command)
}

// int32 value = 2;
inline void PTUCommand::clear_value() {
  _impl_.value_ = 0;
}
inline int32_t PTUCommand::_internal_value() const {
  return _impl_.value_;
}
inline int32_t PTUCommand::value() const {
  // @@protoc_insertion_point(field_get:ptu.PTUCommand.value)
  return _internal_value();
}
inline void PTUCommand::_internal_set_value(int32_t value) {
  
  _impl_.value_ = value;
}
inline void PTUCommand::set_value(int32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:ptu.PTUCommand.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ptu

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ptu::PTUType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ptu::PTUType>() {
  return ::ptu::PTUType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ptu_2eproto
