syntax = "proto3";

package ptu;

message PTUStatus {
    int32 pan_units = 1;
    int32 tilt_units = 2;
    double pan_degrees_per_unit = 3;
    double tilt_degrees_per_unit = 4;
    int32 pan_heading = 5;
    int32 tilt_heading = 6;
    int32 port = 7;
    int32 pan_min_deg = 8;
    int32 pan_max_deg = 9;
    int32 tilt_min_deg = 10;
    int32 tilt_max_deg = 11;
    int32 pan_speed = 12;
    int32 tilt_speed = 13;
}

enum PTUType {
    UNKNOWN = 0;
    HOME = 1;
    STOP = 2;
    SET_PAN = 3;
    SET_TILT = 4;
    SET_PAN_HEADING = 5;
    SET_TILT_HEADING = 6;
}

message PTUCommand {
    PTUType command = 1;
    int32 value = 2;
}
